# Generated by Django 5.1 on 2024-09-14 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=30)),
                ('longName', models.CharField(max_length=500)),
                ('status', models.CharField(default='', max_length=10)),
                ('shortName', models.CharField(max_length=500)),
                ('closePrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('priceToBook', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fiftyTwoWeekLow', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fiftyTwoWeekHigh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pct_change', models.DecimalField(decimal_places=4, max_digits=10)),
                ('rs_change', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='GraphDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datetime', to='stockData.graph')),
            ],
        ),
        migrations.CreateModel(
            name='GraphDateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.DecimalField(decimal_places=2, max_digits=10)),
                ('high', models.DecimalField(decimal_places=2, max_digits=10)),
                ('low', models.DecimalField(decimal_places=2, max_digits=10)),
                ('close', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adj_close', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.BigIntegerField()),
                ('datedata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datetimedata', to='stockData.graphdate')),
            ],
        ),
    ]
