# Generated by Django 5.1 on 2024-09-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='priceToBook',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
