# Generated by Django 5.1 on 2024-09-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userStockData', '0002_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstock',
            name='purchase_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userstock',
            name='sell_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
