# Generated by Django 5.1 on 2024-09-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userStockData', '0003_alter_userstock_purchase_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstock',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='stock',
        ),
        migrations.AddField(
            model_name='userstock',
            name='ticker',
            field=models.CharField(default='^NSC', max_length=50),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='ticker',
            field=models.CharField(default='^NSC', max_length=50),
        ),
        migrations.AlterField(
            model_name='userstock',
            name='shares',
            field=models.IntegerField(default=1),
        ),
    ]
